import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  Bell,
  Box,
  Building,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Circle,
  Clock,
  Copy,
  Cpu,
  Download,
  ExternalLink,
  Eye,
  FileText,
  Filter,
  GitBranch,
  Hash,
  History,
  LayoutGrid,
  List,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize,
  Menu,
  MoreHorizontal,
  Moon,
  PanelLeft,
  Pencil,
  Plus,
  Printer,
  QrCode,
  RotateCw,
  ScanLine,
  Search,
  Server,
  Settings,
  Shield,
  Sliders,
  Sun,
  Upload,
  Users,
  WifiOff,
  Wrench,
  X,
  ZapIcon,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  "activity": Activity,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "bell": Bell,
  "box": Box,
  "building": Building,
  "check": Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevrons-up-down": ChevronsUpDown,
  "circle": Circle,
  "clock": Clock,
  "copy": Copy,
  "cpu": Cpu,
  "dot": Circle,
  "download": Download,
  "external-link": ExternalLink,
  "eye": Eye,
  "file-text": FileText,
  "filter": Filter,
  "git-branch": GitBranch,
  "hash": Hash,
  "history": History,
  "layout-grid": LayoutGrid,
  "list": List,
  "lock": Lock,
  "logout": LogOut,
  "mail": Mail,
  "map-pin": MapPin,
  "maximize": Maximize,
  "menu": Menu,
  "more-horizontal": MoreHorizontal,
  "moon": Moon,
  "panel-left": PanelLeft,
  "pencil": Pencil,
  "plus": Plus,
  "printer": Printer,
  "qr-code": QrCode,
  "rotate": RotateCw,
  "scan-line": ScanLine,
  "search": Search,
  "server": Server,
  "settings": Settings,
  "shield": Shield,
  "sliders": Sliders,
  "sort": List,
  "sun": Sun,
  "upload": Upload,
  "users": Users,
  "wifi-off": WifiOff,
  "wrench": Wrench,
  "x": X,
  "zap": ZapIcon,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export interface IconProps {
  name: IconName;
  size?: number;
  className?: string;
  strokeWidth?: number;
  style?: React.CSSProperties;
}

export function Icon({ name, size = 16, className, strokeWidth = 1.9, style }: IconProps) {
  const Cmp = ICONS[name] ?? Circle;
  return <Cmp className={className} size={size} strokeWidth={strokeWidth} style={style} />;
}
